name: Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: "*"

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Docker stuff
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: ghcr.io/whylabs/artifact-server:${{ github.sha }}
          outputs: type=docker,dest=/tmp/artifact-server.tar
      - name: Upload container artifact
        uses: actions/upload-artifact@v2
        with:
          name: container
          path: /tmp/artifact-server.tar
      - name: Print container tag
        run: echo "Using tag ${{ github.sha }}"

  publish_docker_image:
    name: Publish the Docker image to Github
    if: ${{ !github.event.act && github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_REGISTRY_PASSWORD }}
      - name: Download container artifact
        uses: actions/download-artifact@v2
        with:
          name: container
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/artifact-server.tar
          docker tag ghcr.io/whylabs/artifact-server:${{github.sha}} ghcr.io/whylabs/artifact-server:latest
          docker image ls -a
      - name: Push Docker container
        run: |
          docker push ghcr.io/whylabs/artifact-server:${{github.sha}}
          docker push ghcr.io/whylabs/artifact-server:latest
